[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = 'cancun'

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

fs_permissions = [
  { access = "read", path = "./out/" },
  { access = "read", path = "./script/input/" },
  { access = "read-write", path = "./script/output/" },
]


[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
anvil = "localhost:8545"

[etherscan]
# sepolia = { key = "${ETHERSCAN_API_KEY}" }