[profile.default]
src = "pht"
out = "out_pht"
libs = ["lib"]
evm_version = 'istanbul'
optimizer = true
optimizer_runs = 200
auto_detect_solc = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
fs_permissions = [
    { access = "read", path = "./out_pht/" },
    { access = "read", path = "./script/input/" },
    { access = "read", path = "./config/" },
    { access = "read-write", path = "./script/output/" },
]


[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
anvil = "localhost:8545"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }

[profile.mcd]
src = "src"
test = "src/test"
out = "out_mcd"
libs = []
solc = "0.6.12"
# @TODO cancun might not make sense for mcd codebase
# consider switching to whatever was used at deployment
# time for DAI
evm_version = 'istanbul'
auto_detect_solc = false
optimizer = true
optimizer_runs = 200
